image: openjdk:11

stages:
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  image: gradle
  stage: test
  script:
    - gradle check

after_script:
  - echo "End CI"