image: gradle:6.7.1-jdk-11

stages:
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: test
  script:
    - gradle test

after_script:
  - echo "End CI"