spring:
  datasource:
    username: serwis_aukcyjny
    password: serwis_aukcyjny
    url: jdbc:mysql://localhost:4000/serwis_aukcyjny?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: serwisaukcyjny4@gmail.com
    password: fdyvcxxmndrnlxku
    properties.mail.smtp:
      auth: true
      starttls.enable: true
keycloak:
  realm: serwis-aukcyjny
  auth-server-url: http://localhost:8000/auth
  resource: webapp
  public-client: false
  ssl-required: external
  principal-attribute: preferred_username
  credentials:
    secret: 1a1c1b88-d29c-44e2-a005-fe246bf39e90
auth:
  keycloak:
    management:
      clientId: admin-cli
      serverUrl: ${keycloak.auth-server-url}
      realm: ${keycloak.realm}
      masterRealm: master
      username: admin
      password: admin
  cors:
    allowedOrigin: http://localhost:4200
app:
  message:
    sendCron: 0 0/1 * 1/1 * ?
    cleanCron: 0 0 12 * * ?
    maxTries: 3
  web:
    guiUrl: http://localhost:4200
  dashboard:
    limit: 10
  auction:
    maxPromoted: 10
    duration: 14