spring:
  datasource:
    username: serwis_aukcyjny
    password: serwis_aukcyjny
    url: jdbc:mysql://localhost:4000/serwis_aukcyjny?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: update
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration