spring:
  datasource:
    username: serwis_aukcyjny
    password: serwis_aukcyjny
    url: jdbc:mysql://localhost:4000/serwis_aukcyjny?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: serwisaukcyjny4@gmail.com
    password: cbexogvpzrpyhrio
    properties.mail.smtp:
      auth: true
      starttls.enable: true
keycloak:
  realm: Serwis-aukcyjny
  auth-server-url: http://localhost:8000/auth
  resource: webapp
  public-client: false
  ssl-required: external
  principal-attribute: preferred_username
  credentials:
    secret: 37ef7fba-f9cb-4a44-b7e5-bab4a3ce9255
  bearer-only: true
auth:
  keycloak:
    management:
      clientId: admin-cli
      serverUrl: ${keycloak.auth-server-url}
      realm: ${keycloak.realm}
      masterRealm: master
      username: admin
      password: admin
  cors:
    allowedOrigin: http://localhost:4200
app:
  message:
    sendCron: 0 0/1 * 1/1 * ?
    cleanCron: 0 0 12 * * ?
    maxTries: 3
  web:
    guiUrl: http://localhost:4200
  auction:
    maxPromoted: 10
    duration: 14
    expiredCheckCron: 0/60 * * * * ?
    startCheckCron: 0/60 * * * * ?
    reminderCheckCron: 0 0 * * * *
  photo:
    destination: serwis-aukcyjny-photo
  premium:
    price: 15
    duration: 30
    cleanerCron: 0 0 * * * *
pay:
  paypal:
    clientId:
    clientSecret:
    environment: sandbox
    successRedirectUrl: http://localhost:8080/api/pay/success
    cancelRedirectUrl: http://localhost:8080/api/pay/cancel
