spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/serwis_aukcyjny?useSSL=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration